CREATE TABLE `doc_integrity_section` (
	`id` int AUTO_INCREMENT NOT NULL,
	`eyebrowText` varchar(100),
	`headingLine1` varchar(150),
	`headingLine2` varchar(150),
	`bodyText` text,
	`cardBadge` varchar(50),
	`cardSubtext` varchar(100),
	`cardTitle` varchar(150),
	`cardDetail` varchar(300),
	`heroImageUrl` varchar(500),
	`heroImageKey` varchar(500),
	`callout1Position` enum('top','middle','bottom') DEFAULT 'top',
	`callout1Title` varchar(100),
	`callout1Description` varchar(300),
	`callout2Position` enum('top','middle','bottom') DEFAULT 'middle',
	`callout2Title` varchar(100),
	`callout2Description` varchar(300),
	`callout3Position` enum('top','middle','bottom') DEFAULT 'bottom',
	`callout3Title` varchar(100),
	`callout3Description` varchar(300),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `doc_integrity_section_id` PRIMARY KEY(`id`)
);
